[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_NHOST_SUBDOMAIN = "${VITE_NHOST_SUBDOMAIN}"
  VITE_NHOST_REGION = "${VITE_NHOST_REGION}"
  VITE_HASURA_GRAPHQL_URL = "${VITE_HASURA_GRAPHQL_URL}"
  VITE_HASURA_GRAPHQL_WS = "${VITE_HASURA_GRAPHQL_WS}"
  VITE_HASURA_ACTION_SENDMESSAGE = "${VITE_HASURA_ACTION_SENDMESSAGE}"
